include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    avoid_print: false
    cascade_invocations: false
    avoid_dynamic_calls: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_constructors_first: false
